# Generated by Django 2.2.6 on 2019-11-12 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CAPAPPv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reserved_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='reserved_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='room_type',
            field=models.CharField(choices=[('E', 'Engineering'), ('H', 'Humanities'), ('B', 'Business')], default=None, max_length=1),
        ),
    ]
